### PR TITLE
Fixed single-quote formatting for news.

### LINKED ISSUE #104: Single Quote Doesn't Display News Titles
On the website, a news title that should contain a single quote instead has the sequence '&#39' where a single quote should be.

### PR DESCRIPTION
**Pull request by nssafir**
Quotes in single news titles are presented correctly instead of as '&#39'.

### CODE REVIEW

**Review by daperlmut — APPROVED** [review]

File: src/main/java/com/google/sps/servlets/NewsServlet.java [hunk 1]
```diff
@@ -126,6 +126,7 @@ public String getHTML(HttpURLConnection connection) throws IOException {
       lastSubstring = substrings[i - 1];
       thisSubstring = substrings[i];
       title = thisSubstring.substring(thisSubstring.indexOf(">") + 1, thisSubstring.indexOf("<"));
+      title = title.replace("&#39;", "'");
```
Comment (daperlmut) [inline src/main/java/com/google/sps/servlets/NewsServlet.java:130]: [Optional] Might be worth adding a note discussing why this has to handled specially.

**Review by juanuribe28 — APPROVED** [review]
