### PR TITLE
Fix duplicate keywords

### LINKED ISSUE #49: Repeated Keywords
In some cases the same keyword appears multiple times.

### PR DESCRIPTION
**Pull request by dranilew**
Using a set instead of a list shoudl fix this issue. However, it still would not be able to discern between, for example, "every day" vs. "everyday".

### CODE REVIEW

**Review by juanuribe28 — APPROVED** [review]

File: src/main/java/com/google/sps/data/Keywords.java [hunk 1]
```diff
@@ -99,9 +99,9 @@ private static String addToDatastore(String message) throws IOException {
       orderSet.add(entity);
     }
     // We must create a new list of Strings as a collection of NLP Entities is not supported by datastore.
-    List<String> keywordList = new ArrayList<>();
+    Set<String> keywordList = new HashSet<>();
```
Comment (juanuribe28) [inline src/main/java/com/google/sps/data/Keywords.java]: I would change the name to keywordSet

**Review by juanuribe28 — APPROVED** [review]

**Review by daperlmut — APPROVED** [review]
